### ISSUE TITLE
디자인 시안 만들기

### ISSUE THREAD

**Issue by seumomo** [FRONTENDSCHOOL6/Lionly#2]

**Comment by seumomo** [comment]
**디자인 시안 완료**
1. 랜딩
2. 로그인
3. 회원가입
4. 피드
5. 글쓰기
6. 마이페이지 - 프로필 수정 
7. 마이페이지 - 내 글 보기

**디자인 시안 미완료**
1. 계정 찾기
2. 글 선택 시

**Comment by itzwe** [comment]
**디자인 시안 최종 완료**
1. 랜딩
2. 로그인
3. 회원가입
4. 피드
5. 글쓰기
6. 마이페이지 - 프로필 수정 
7. 마이페이지 - 내 글 보기
8. 계정 찾기
9. 글 선택 시
