### ISSUE TITLE
코드 수정 후 같은 오류만 발생하는 현상

### ISSUE THREAD

**Issue by chowonn** [FRONTENDSCHOOL6/Lionly#23]
## 🐞 문제점
포켓호스트에서 데이터를 불러오는 과정 중에서 코드를 여러 차례 수정해도 같은 오류만 발생하는 현상이 있었습니다. (아래와 같은 오류만 계속 발생하는 현상)

## 📸 스크린샷
![image](https://github.com/FRONTENDSCHOOL6/Lionly/assets/70478015/deb40524-a747-4f93-8410-e4e593501952)

## ✔ 해결방안
- 타입 에러가 발생한 것으로, 각각의 데이터 propTypes를 설정해주면 타입 체크 후 오류 원인을 자세하게 확인할 수 있었습니다.
 
![image](https://github.com/FRONTENDSCHOOL6/Lionly/assets/70478015/db0a1bf9-62ab-4ff8-9deb-dc1ce070b76f)
![image](https://github.com/FRONTENDSCHOOL6/Lionly/assets/70478015/326b6cc0-f830-4c55-a889-5cb2e0bcae86)

**Comment by seumomo** [comment]
`Cannot read property~` 에러는 타입검사가 안 됐기 때문인 건가요?

**Comment by itzwe** [comment]
데이터 문제인줄 알았는데 타입 문제였나보네요

**Comment by chowonn** [comment]
네 맞습니다. 
Cannot read property~ 에러는 타입검사가 안되어서 그걸 처리해주지 못해서 계속 같은 오류가 발생했었고 propTypes로 처리해주니 해당 오류 해결된 후 다른 원인을 확인할 수 있었습니다!

**Comment by chowonn** [comment]
> `Cannot read property~` 에러는 타입검사가 안 됐기 때문인 건가요?
