### ISSUE TITLE
[Fix] useRef를 활용한 Input에서 비밀번호 확인  유효성 검사

### ISSUE THREAD

**Issue by seumomo** [FRONTENDSCHOOL6/Lionly#24]
## 🐞 문제점
useRef를 활용하여 Input Component를 구성한 상태에서,
`비밀번호 확인`의 유효성 검사에서 `비밀번호`의 값을 받아오지 못하는 상황

## ✔ 해결방안
![code](https://github.com/FRONTENDSCHOOL6/Lionly/assets/127176650/7a5ee60b-6709-4521-af8b-a41c8814fb14)
1. 조건문 바깥에서 사용할 수 있도록 `let`으로 변수인 `password` 선언합니다.
2. 조건문을 사용하여, `name`이 `userPasswordCheck`일 때만 코드가 동작하도록 합니다.
3. 문서에서 `name`이 `userPassWord`인 요소의 `value`를 `password`에 할당합니다.
4. 해당 요소가 존재하지 않는 경우를 대비해 `?`를 사용합니다.

![code1](https://github.com/FRONTENDSCHOOL6/Lionly/assets/127176650/949909d1-3acf-45fd-9bd2-f9f8087dec93)
위에서 만든 변수 `password`와 `inputValue`를 비교하는 유효성 검사를 설정합니다.

---

`input`의 `name`이 `userPassWord`와 `userPasswordCheck` 통일성이 부족해 보이는데,
`userPassword~`로 통일하면 어떨까요?

`input`의 `name`이 `ansWer`도 특별한 사유가 없으시다면,
`answer`로 하는 게 좋지 않을까 합니다!

**Comment by jisulee97** [comment]
넵 확인했고 수정해보겠습니다 코멘트 감사드립니다
