### ISSUE TITLE
데이터 스키마 만들기

### ISSUE THREAD

**Issue by seumomo** [FRONTENDSCHOOL6/Lionly#4]

**Comment by seumomo** [comment]
데이터 배포 주소 : https://lionly.pockethost.io/_/#/collections?collectionId=_pb_users_auth_&filter=&sort=-created

**Comment by jisulee97** [comment]
넵 확인했습니다 정상 작동 되고 데이터 부분은 네명이서 다 같이 모였을 때 의논해보는게 좋을거 같습니다!

**Comment by seumomo** [comment]
데이터 스키마 초안 구성 완료
